export interface Book {
  goodreadsId: string
  libbyId?: string
  title: string
  author: string
  cover?: { href: string; primaryColour: string }
  description?: string
  genres?: string[]
  libraries: Library[]
}

interface Library {
  name: string
  waittime?: string
  holdtime?: string
  loaned?: boolean
}

export interface ProcessingLibraryBooks {
  syncId: string
  step: number
  totalSteps: number
  books: Book[]
  failed?: boolean
  libraryNames: string[]
}

export interface LibraryBooks {
  updatedAt: string
  books: Book[]
  libraryNames: string[]
}

export const RAW_GOODREADS_BOOK = {
  "Book Id": "50359667",
  Title:
    "Confessions of a Forty-Something F**k Up: The Funniest WTF AM I DOING?! Novel of the Year",
  Author: "Alexandra Potter",
  "Author l-f": "Potter, Alexandra",
  "Additional Authors": "",
  ISBN: '=""',
  ISBN13: '=""',
  "My Rating": "0",
  "Average Rating": "4.21",
  Publisher: "Macmillan",
  Binding: "Kindle Edition",
  "Number of Pages": "",
  "Year Published": "2020",
  "Original Publication Year": "2020",
  "Date Read": "",
  "Date Added": "2020/08/15",
  Bookshelves: "to-read",
  "Bookshelves with positions": "to-read (#17)",
  "Exclusive Shelf": "to-read",
  "My Review": "",
  Spoiler: "",
  "Private Notes": "",
  "Read Count": "0",
  "Recommended For": "",
  "Recommended By": "",
  "Owned Copies": "0",
  "Original Purchase Date": "",
  "Original Purchase Location": "",
  Condition: "",
  "Condition Description": "",
  BCID: "",
}

export type GoodreadsBook = typeof RAW_GOODREADS_BOOK

const LIBBY_SYNC_RESPONSE = {
  result: "synchronized",
  cards: [
    {
      cardId: "30238327",
      cardName: "29065038707097",
      createDate: "2020-07-26T01:53:55+00:00",
      authorizeDate: "2021-07-03T23:04:53Z",
      puid: "82753696",
      isSessionUser: false,
      library: [Object],
      advantageKey: "calgary",
      ilsName: "calgary",
      username: "29065038707097",
      emailAddress: null,
      limits: [Object],
      counts: [Object],
      lendingPeriods: [Object],
      accounts: [Array],
      contentMask: -1,
      isVisitingCard: false,
      canPlaceHolds: true,
      canRecommendTitles: true,
      publicLibraryMaturity: 200,
    },
    {
      cardId: "38683056",
      cardName: "29100700209039",
      createDate: "2021-03-23T03:34:45+00:00",
      authorizeDate: "2021-07-03T23:04:48Z",
      puid: "93198746",
      isSessionUser: false,
      library: [Object],
      advantageKey: "toronto",
      ilsName: "toronto",
      username: "29100700209039",
      emailAddress: null,
      limits: [Object],
      counts: [Object],
      lendingPeriods: [Object],
      accounts: [Array],
      contentMask: -1,
      isVisitingCard: false,
      canPlaceHolds: true,
      canRecommendTitles: true,
      publicLibraryMaturity: 200,
    },
  ],
  loans: [
    {
      firstCreatorId: 376472,
      renewableOn: "2021-07-19T18:47:36Z",
      checkoutDate: "2021-07-01T18:47:36Z",
      expireDate: "2021-07-22T18:47:36Z",
      expires: "2021-07-22T18:47:36Z",
      isLuckyDayCheckout: false,
      isHoldable: true,
      isOwned: true,
      isAssigned: false,
      isBundledChild: false,
      isFormatLockedIn: true,
      isReturnable: true,
      privateAccountId: -1,
      luckyDayOwnedCopies: 0,
      luckyDayAvailableCopies: 0,
      ownedCopies: 2,
      availableCopies: 0,
      checkoutId: 67909263,
      sample: [Object],
      bundledContent: [],
      overDriveFormat: [Object],
      otherFormats: [Array],
      readiverseFormat: [Object],
      subjects: [Array],
      constraints: [Object],
      type: [Object],
      covers: [Object],
      formats: [Array],
      publisherAccount: [Object],
      id: "520136",
      firstCreatorName: "Keigo Higashino",
      title: "The Devotion of Suspect X",
      sortTitle: "Devotion of Suspect X Detective Galileo Series Book 01",
      starRating: 4.1,
      starRatingCount: 110,
      publishDate: "2011-02-01T05:00:00Z",
      publishDateText: "02/01/2011",
      holdsCount: 4,
      availabilityType: "normal",
      series: "Detective Galileo",
      subtitle: "Detective Galileo Series, Book 1",
      reserveId: "e8ed2735-d452-40f2-a5a6-0430c144a34b",
      websiteId: "153",
      cardId: "30238327",
    },
  ],
  holds: [
    {
      firstCreatorId: 376472,
      placedDate: "2021-07-02T16:57:44.670Z",
      isHoldable: true,
      isOwned: true,
      isFastlane: false,
      isAvailable: false,
      isPreReleaseTitle: false,
      suspensionFlag: false,
      autoRenewFlag: false,
      autoCheckoutFlag: false,
      holdListPosition: 1,
      holdsCount: 1,
      sample: [Object],
      overDriveFormat: [Object],
      otherFormats: [Array],
      readiverseFormat: [Object],
      subjects: [Array],
      type: [Object],
      covers: [Object],
      formats: [Array],
      publisherAccount: [Object],
      id: "857855",
      firstCreatorName: "Keigo Higashino",
      title: "Salvation of a Saint",
      sortTitle: "Salvation of a Saint Detective Galileo Series Book 02",
      starRating: 4.4,
      starRatingCount: 56,
      publishDate: "2012-10-02T04:00:00Z",
      publishDateText: "10/02/2012",
      redeliveriesRequestedCount: 0,
      redeliveriesAutomatedCount: 0,
      luckyDayAvailableCopies: 0,
      luckyDayOwnedCopies: 0,
      availableCopies: 0,
      patronHoldsRatio: 1,
      estimatedWaitDays: 14,
      holdsRatio: 1,
      estimatedReleaseDate: "2012-10-02T04:00:00Z",
      ownedCopies: 1,
      series: "Detective Galileo",
      subtitle: "Detective Galileo Series, Book 2",
      cardId: "30238327",
    },
    {
      firstCreatorId: 1644558,
      placedDate: "2021-06-27T15:13:40.380Z",
      isHoldable: true,
      isOwned: true,
      isFastlane: false,
      isAvailable: false,
      isPreReleaseTitle: false,
      suspensionFlag: false,
      autoRenewFlag: false,
      autoCheckoutFlag: false,
      holdListPosition: 198,
      holdsCount: 283,
      sample: [Object],
      overDriveFormat: [Object],
      otherFormats: [Array],
      readiverseFormat: [Object],
      subjects: [Array],
      type: [Object],
      covers: [Object],
      formats: [Array],
      publisherAccount: [Object],
      id: "5460613",
      firstCreatorName: "Alex Michaelides",
      title: "The Maidens",
      sortTitle: "Maidens",
      starRating: 3.4,
      starRatingCount: 78,
      publishDate: "2021-06-15T00:00:00Z",
      publishDateText: "06/15/2021",
      redeliveriesRequestedCount: 0,
      redeliveriesAutomatedCount: 0,
      luckyDayAvailableCopies: 0,
      luckyDayOwnedCopies: 20,
      availableCopies: 0,
      patronHoldsRatio: 4,
      estimatedWaitDays: 45,
      holdsRatio: 5,
      estimatedReleaseDate: "2021-06-15T00:00:00Z",
      ownedCopies: 60,
      cardId: "38683056",
    },
    {
      firstCreatorId: 659166,
      placedDate: "2021-06-25T13:43:56.360Z",
      isHoldable: true,
      isOwned: true,
      isFastlane: false,
      isAvailable: false,
      isPreReleaseTitle: false,
      suspensionFlag: false,
      autoRenewFlag: false,
      autoCheckoutFlag: false,
      holdListPosition: 581,
      holdsCount: 722,
      sample: [Object],
      overDriveFormat: [Object],
      otherFormats: [Array],
      readiverseFormat: [Object],
      subjects: [Array],
      type: [Object],
      covers: [Object],
      formats: [Array],
      publisherAccount: [Object],
      id: "5665700",
      firstCreatorName: "Andy Weir",
      title: "Project Hail Mary",
      sortTitle: "Project Hail Mary A Novel",
      starRating: 4.5,
      starRatingCount: 455,
      publishDate: "2021-05-04T00:00:00Z",
      publishDateText: "05/04/2021",
      redeliveriesRequestedCount: 0,
      redeliveriesAutomatedCount: 0,
      luckyDayAvailableCopies: 0,
      luckyDayOwnedCopies: 0,
      availableCopies: 0,
      patronHoldsRatio: 6,
      estimatedWaitDays: 80,
      holdsRatio: 8,
      estimatedReleaseDate: "2021-05-04T04:00:00Z",
      ownedCopies: 100,
      subtitle: "A Novel",
      cardId: "38683056",
    },
    {
      firstCreatorId: 2304056,
      placedDate: "2021-05-30T14:56:05.597Z",
      isHoldable: true,
      isOwned: true,
      isFastlane: false,
      isAvailable: false,
      isPreReleaseTitle: false,
      suspensionFlag: false,
      autoRenewFlag: false,
      autoCheckoutFlag: false,
      holdListPosition: 50,
      holdsCount: 136,
      sample: [Object],
      overDriveFormat: [Object],
      otherFormats: [Array],
      readiverseFormat: [Object],
      subjects: [Array],
      type: [Object],
      covers: [Object],
      formats: [Array],
      publisherAccount: [Object],
      id: "5665286",
      firstCreatorName: "Mia P. Manansala",
      title: "Arsenic and Adobo",
      sortTitle: "Arsenic and Adobo Tita Rosies Kitchen Mystery Series Book 01",
      starRating: 3.5,
      starRatingCount: 74,
      publishDate: "2021-05-04T00:00:00Z",
      publishDateText: "05/04/2021",
      redeliveriesRequestedCount: 0,
      redeliveriesAutomatedCount: 0,
      luckyDayAvailableCopies: 0,
      luckyDayOwnedCopies: 6,
      availableCopies: 0,
      patronHoldsRatio: 3,
      estimatedWaitDays: 30,
      holdsRatio: 7,
      estimatedReleaseDate: "2021-05-04T00:00:00Z",
      ownedCopies: 22,
      series: "Tita Rosie's Kitchen Mystery",
      subtitle: "Tita Rosie's Kitchen Mystery Series, Book 1",
      cardId: "38683056",
    },
    {
      firstCreatorId: 2354799,
      placedDate: "2021-05-12T20:12:13.647Z",
      isHoldable: true,
      isOwned: true,
      isFastlane: false,
      isAvailable: false,
      isPreReleaseTitle: false,
      suspensionFlag: false,
      autoRenewFlag: false,
      autoCheckoutFlag: false,
      holdListPosition: 52,
      holdsCount: 272,
      sample: [Object],
      overDriveFormat: [Object],
      otherFormats: [Array],
      readiverseFormat: [Object],
      subjects: [Array],
      type: [Object],
      covers: [Object],
      formats: [Array],
      publisherAccount: [Object],
      id: "5745414",
      firstCreatorName: "Jesse Q. Sutanto",
      title: "Dial a for Aunties",
      sortTitle: "Dial a for Aunties",
      starRating: 3.6,
      starRatingCount: 95,
      publishDate: "2021-04-27T00:00:00Z",
      publishDateText: "04/27/2021",
      redeliveriesRequestedCount: 0,
      redeliveriesAutomatedCount: 0,
      luckyDayAvailableCopies: 0,
      luckyDayOwnedCopies: 7,
      availableCopies: 0,
      patronHoldsRatio: 2,
      estimatedWaitDays: 17,
      holdsRatio: 8,
      estimatedReleaseDate: "2021-04-27T04:00:00Z",
      ownedCopies: 38,
      cardId: "38683056",
    },
  ],
  summary: {
    "30238327": { cards: "done", loans: "done", holds: "done" },
    "38683056": { cards: "done", loans: "done", holds: "done" },
  },
  identity:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJyZWFkaXZlcnNlIiwiaXNzIjoic2VudHJ5IiwiY2hpcCI6eyJpZCI6ImU2MjBlNDQwLTQ5MjItNDk1Ni05ZDcwLTllOWUyZjg0NzFmMiIsInByaSI6ImU2MjBlNDQwLTQ5MjItNDk1Ni05ZDcwLTllOWUyZjg0NzFmMiIsImFnIjpudWxsLCJhY2NvdW50cyI6W3siYWciOjEwMjMxMTY3LCJpZCI6IjQ1MjM2MzM1IiwidHlwIjoibGlicmFyeSIsImNhcmRzIjpbeyJpZCI6IjMwMjM4MzI3IiwibmFtZSI6IjI5MDY1MDM4NzA3MDk3IiwibGliIjp7ImlkIjoiMTUzIiwia2V5IjoiY2FsZ2FyeSJ9fV19LHsiYWciOjEwMjMxMTY3LCJpZCI6IjU0MjA1MTQzIiwidHlwIjoibGlicmFyeSIsImNhcmRzIjpbeyJpZCI6IjM4NjgzMDU2IiwibmFtZSI6IjI5MTAwNzAwMjA5MDM5IiwibGliIjp7ImlkIjoiMjQzIiwia2V5IjoidG9yb250byJ9fV19XX19.xKe5k04WKOR1XDUNqf1cr12z_q0I-82mAfdpq4cfusKyoLRnWji2y3MF0xPoe5kQ7eapPn9jF9fJbTFSvrxQzmpqSPvjWKAlfPQlD_7XvowGJhDrhVvDxu6h1Rv7TJR3muqxKjaMYDTagVw75-jt0ZK7jWFK5ZONGcalKWi8l1ba22tpxL8RHE6gubvSYQQ_umF1h3O3klX0bfQPyPZ3saOFLbP8UcGMV2na5g8-eDZVVO0SXXZEDKeGHBkzMxxAU20L-CqoaeCSkFHmQpZqz4ccM4ZK94YbY-PSCzYaZZRuIT8ZObn3YnqpsjyS9h880g0Eg9gzObzHbFm4_6ZozA",
}

export type LibbySyncResponse = typeof LIBBY_SYNC_RESPONSE

const OVERDRIVE_SEARCH_RESPONSE = {
  totalItems: 2,
  queryKeys: {},
  facets: {
    appliedCount: 0,
    availability: {
      items: [
        {
          isApplied: true,
          totalItemsText: "2",
          id: "all-titles",
          name: "All titles",
          totalItems: 2,
        },
        {
          isApplied: false,
          totalItemsText: "",
          id: "available-now",
          name: "Available now",
        },
      ],
      name: "Availability",
    },
    mediaTypes: {
      items: [
        {
          isApplied: false,
          totalItemsText: "1",
          id: "ebook",
          name: "eBook",
          totalItems: 1,
        },
        {
          isApplied: false,
          totalItemsText: "1",
          id: "audiobook",
          name: "Audiobook",
          totalItems: 1,
        },
      ],
      name: "Media type",
    },
    formats: {
      items: [
        {
          isApplied: false,
          totalItemsText: "1",
          id: "ebook-overdrive",
          name: "OverDrive Read",
          totalItems: 1,
        },
        {
          isApplied: false,
          totalItemsText: "1",
          id: "ebook-epub-adobe",
          name: "EPUB eBook",
          totalItems: 1,
        },
        {
          isApplied: false,
          totalItemsText: "1",
          id: "audiobook-overdrive",
          name: "OverDrive Listen audiobook",
          totalItems: 1,
        },
        {
          isApplied: false,
          totalItemsText: "1",
          id: "audiobook-mp3",
          name: "MP3 audiobook",
          totalItems: 1,
        },
        {
          isApplied: false,
          totalItemsText: "1",
          id: "ebook-kobo",
          name: "Kobo eBook",
          totalItems: 1,
        },
      ],
      name: "Format",
    },
    maturityLevels: {
      items: [
        {
          isApplied: false,
          totalItemsText: "2",
          id: "generalcontent",
          name: "General adult",
          totalItems: 2,
        },
      ],
      name: "Audience",
    },
    subjects: {
      items: [
        {
          isApplied: false,
          totalItemsText: "2",
          id: "26",
          name: "Fiction",
          totalItems: 2,
        },
        {
          isApplied: false,
          totalItemsText: "2",
          id: "57",
          name: "Mystery",
          totalItems: 2,
        },
        {
          isApplied: false,
          totalItemsText: "1",
          id: "49",
          name: "Literature",
          totalItems: 1,
        },
      ],
      name: "Subject",
    },
    bisacCodes: {
      items: [
        {
          isApplied: false,
          totalItemsText: "2",
          id: "FIC022020",
          name: "Fiction / Mystery & Detective / Police Procedural",
          totalItems: 2,
        },
        {
          isApplied: false,
          totalItemsText: "2",
          id: "FIC022080",
          name: "FICTION / Mystery & Detective / International Crime & Mystery",
          totalItems: 2,
        },
        {
          isApplied: false,
          totalItemsText: "1",
          id: "FIC108000",
          name: "Fiction/ World Literature / Japan",
          totalItems: 1,
        },
      ],
      name: "Bisac code",
    },
    languages: {
      items: [
        {
          isApplied: false,
          totalItemsText: "2",
          id: "en",
          name: "English",
          totalItems: 2,
        },
      ],
      name: "Language",
    },
    boolean: {
      items: [
        {
          isApplied: false,
          totalItemsText: "2",
          id: "f",
          name: "Does not have audio synchronized text",
          totalItems: 2,
        },
      ],
      name: "Boolean properties",
    },
    addedDates: {
      items: [
        {
          isApplied: false,
          totalItemsText: "0",
          id: "days-0-7",
          name: "Last 7 days",
          totalItems: 0,
        },
        {
          isApplied: false,
          totalItemsText: "0",
          id: "days-0-14",
          name: "Last 14 days",
          totalItems: 0,
        },
        {
          isApplied: false,
          totalItemsText: "0",
          id: "days-0-30",
          name: "Last 30 days",
          totalItems: 0,
        },
        {
          isApplied: false,
          totalItemsText: "0",
          id: "days-0-90",
          name: "Last 3 months",
          totalItems: 0,
        },
        {
          isApplied: false,
          totalItemsText: "0",
          id: "days-0-180",
          name: "Last 6 months",
          totalItems: 0,
        },
      ],
      name: "Date added",
    },
    atosLevels: { items: [], name: "ATOS Level" },
    lexileScores: { items: [], name: "Lexile Score" },
    interestLevels: { items: [], name: "Interest Level" },
    gradeLevels: { items: [], name: "Text Difficulty" },
    awards: { items: [], name: "Award" },
    jurisdiction: { items: [], name: "Jurisdiction" },
    practiceArea: { items: [], name: "Practice Area" },
    classification: { items: [], name: "Classification" },
  },
  sortOptions: [
    { isApplied: false, id: "mostpopular", name: "Popularity" },
    { isApplied: true, id: "relevance", name: "Relevance" },
    { isApplied: false, id: "releasedate", name: "Release date" },
    { isApplied: false, id: "title", name: "Title" },
    { isApplied: false, id: "author", name: "Author" },
    { isApplied: false, id: "random", name: "Randomized" },
    { isApplied: false, id: "newlyadded", name: "Date added" },
    { isApplied: false, id: "lowcirculating", name: "Low circulating" },
    { isApplied: false, id: "mostpopular-site", name: "Popularity (library)" },
  ],
  items: [
    {
      isAvailable: false,
      isPreReleaseTitle: false,
      isFastlane: false,
      isRecommendableToLibrary: true,
      isOwned: true,
      isHoldable: true,
      visitorEligible: false,
      juvenileEligible: false,
      youngAdultEligible: false,
      firstCreatorId: 376472,
      isBundledChild: false,
      subjects: [
        { name: "Fiction", id: "26" },
        { name: "Literature", id: "49" },
        { name: "Mystery", id: "57" },
      ],
      bisacCodes: ["FIC022020", "FIC022080", "FIC108000"],
      bisac: [
        {
          description: "Fiction / Mystery & Detective / Police Procedural",
          code: "FIC022020",
        },
        {
          description:
            "FICTION / Mystery & Detective / International Crime & Mystery",
          code: "FIC022080",
        },
        { description: "Fiction/ World Literature / Japan", code: "FIC108000" },
      ],
      levels: [],
      creators: [
        { id: 376472, role: "Author", name: "Keigo Higashino" },
        { id: 644665, role: "Narrator", name: "Jeff Woodman" },
        { id: 631418, role: "Translator", name: "Alexander O. Smith" },
      ],
      languages: [{ name: "English", id: "en" }],
      ratings: {
        maturityLevel: { name: "General content", id: "generalcontent" },
        naughtyScore: { name: "General content", id: "GeneralContent" },
      },
      reviewCounts: { publisherSupplier: 0, premium: 2 },
      constraints: { isDisneyEulaRequired: false },
      sample: {
        href: "https://samples.overdrive.com/?crid=A757141C-E442-48F8-9F1E-CFBB40CDB15B&.epub-sample.overdrive.com",
      },
      publisher: { name: "Macmillan Audio", id: "2166" },
      type: { name: "Audiobook", id: "audiobook" },
      covers: {
        cover150Wide: {
          primaryColor: {
            rgb: { blue: 213, green: 214, red: 198 },
            hex: "#C6D6D5",
          },
          width: 150,
          height: 200,
          href: "https://img1.od-cdn.com/ImageType-150/1493-1/A75/714/1C/{A757141C-E442-48F8-9F1E-CFBB40CDB15B}Img150.jpg",
        },
        cover300Wide: {
          primaryColor: {
            rgb: { blue: 213, green: 214, red: 198 },
            hex: "#C6D6D5",
          },
          width: 300,
          height: 400,
          href: "https://img1.od-cdn.com/ImageType-400/1493-1/A75/714/1C/{A757141C-E442-48F8-9F1E-CFBB40CDB15B}Img400.jpg",
        },
        cover510Wide: {
          primaryColor: {
            rgb: { blue: 213, green: 214, red: 198 },
            hex: "#C6D6D5",
          },
          width: 510,
          height: 680,
          href: "https://img1.od-cdn.com/ImageType-100/1493-1/{A757141C-E442-48F8-9F1E-CFBB40CDB15B}Img100.jpg",
        },
      },
      formats: [
        {
          isBundleParent: false,
          hasAudioSynchronizedText: false,
          identifiers: [
            { value: "9781427244321", type: "ISBN" },
            { value: "macmillan_audio#9781427244321", type: "8" },
            { value: "9781427259523", type: "LibraryISBN" },
          ],
          rights: [],
          bundledContent: [],
          sample: {
            href: "https://samples.overdrive.com/?crid=A757141C-E442-48F8-9F1E-CFBB40CDB15B&.epub-sample.overdrive.com",
          },
          id: "audiobook-overdrive",
          name: "OverDrive Listen audiobook",
          onSaleDateUtc: "2014-10-07T00:00:00Z",
          fileSize: 216826144,
          isbn: "9781427259523",
          duration: "07:31:43",
        },
        {
          isBundleParent: false,
          hasAudioSynchronizedText: false,
          identifiers: [
            { value: "9781427244321", type: "ISBN" },
            { value: "macmillan_audio#9781427244321", type: "8" },
            { value: "9781427259523", type: "LibraryISBN" },
          ],
          rights: [],
          bundledContent: [],
          sample: {
            href: "https://excerpts.cdn.overdrive.com/FormatType-425/1493-1/1952908-Malice.mp3",
          },
          id: "audiobook-mp3",
          name: "MP3 audiobook",
          partCount: 7,
          onSaleDateUtc: "2014-10-07T00:00:00Z",
          fileSize: 216855714,
          isbn: "9781427259523",
          duration: "07:31:39",
        },
      ],
      publisherAccount: { name: "Macmillan Audio", id: "3606" },
      estimatedReleaseDate: "2014-10-07T00:00:00Z",
      subtitle: "Detective Kaga Series, Book 4",
      series: "Detective Kaga",
      description:
        "<p>Acclaimed bestselling novelist Kunihiko Hidaka is found brutally murdered in his home on the night before he's planning to leave Japan and relocate to Vancouver. His body is found in his office, a locked room, within his locked house, by his...",
      availableCopies: 0,
      ownedCopies: 3,
      luckyDayAvailableCopies: 0,
      luckyDayOwnedCopies: 0,
      holdsCount: 2,
      holdsRatio: 1,
      estimatedWaitDays: 14,
      availabilityType: "normal",
      id: "1952908",
      firstCreatorName: "Keigo Higashino",
      title: "Malice",
      sortTitle: "Malice Detective Kaga Series Book 04",
      starRating: 3.7,
      starRatingCount: 279,
      edition: "Unabridged",
      publishDate: "2014-10-07T00:00:00Z",
      publishDateText: "10/07/2014",
      reserveId: "a757141c-e442-48f8-9f1e-cfbb40cdb15b",
    },
    {
      isAvailable: false,
      isPreReleaseTitle: false,
      isFastlane: false,
      isRecommendableToLibrary: true,
      isOwned: true,
      isHoldable: true,
      visitorEligible: false,
      juvenileEligible: false,
      youngAdultEligible: false,
      firstCreatorId: 376472,
      isBundledChild: false,
      subjects: [
        { name: "Fiction", id: "26" },
        { name: "Mystery", id: "57" },
      ],
      bisacCodes: ["FIC022020", "FIC022080"],
      bisac: [
        {
          description: "Fiction / Mystery & Detective / Police Procedural",
          code: "FIC022020",
        },
        {
          description:
            "FICTION / Mystery & Detective / International Crime & Mystery",
          code: "FIC022080",
        },
      ],
      levels: [],
      creators: [
        { id: 376472, role: "Author", name: "Keigo Higashino" },
        { id: 631418, role: "Translator", name: "Alexander O. Smith" },
      ],
      languages: [{ name: "English", id: "en" }],
      imprint: { name: "Minotaur Books", id: "129059" },
      ratings: {
        maturityLevel: { name: "General content", id: "generalcontent" },
        naughtyScore: { name: "General content", id: "GeneralContent" },
      },
      reviewCounts: { publisherSupplier: 5, premium: 5 },
      constraints: { isDisneyEulaRequired: false },
      sample: {
        href: "https://samples.overdrive.com/malice-4bf78a?.epub-sample.overdrive.com",
      },
      publisher: { name: "St. Martin's Publishing Group", id: "212797" },
      type: { name: "eBook", id: "ebook" },
      covers: {
        cover150Wide: {
          primaryColor: {
            rgb: { blue: 53, green: 50, red: 35 },
            hex: "#233235",
          },
          width: 150,
          height: 200,
          href: "https://img1.od-cdn.com/ImageType-150/2390-1/4BF/78A/9C/{4BF78A9C-6FAE-4651-BA93-2EF2CFCFDAC5}Img150.jpg",
        },
        cover300Wide: {
          primaryColor: {
            rgb: { blue: 57, green: 45, red: 35 },
            hex: "#232D39",
          },
          width: 300,
          height: 400,
          href: "https://img1.od-cdn.com/ImageType-400/2390-1/4BF/78A/9C/{4BF78A9C-6FAE-4651-BA93-2EF2CFCFDAC5}Img400.jpg",
        },
        cover510Wide: {
          primaryColor: {
            rgb: { blue: 67, green: 46, red: 44 },
            hex: "#2C2E43",
          },
          width: 510,
          height: 680,
          href: "https://img1.od-cdn.com/ImageType-100/2390-1/{4BF78A9C-6FAE-4651-BA93-2EF2CFCFDAC5}Img100.jpg",
        },
      },
      formats: [
        {
          isBundleParent: false,
          hasAudioSynchronizedText: false,
          identifiers: [{ value: "9781250035615", type: "ISBN" }],
          rights: [],
          bundledContent: [],
          sample: {
            href: "https://samples.overdrive.com/malice-4bf78a?.epub-sample.overdrive.com",
          },
          id: "ebook-overdrive",
          name: "OverDrive Read",
          onSaleDateUtc: "2014-10-07T04:00:00Z",
          isbn: "9781250035615",
        },
        {
          isBundleParent: false,
          hasAudioSynchronizedText: false,
          identifiers: [{ value: "9781250035615", type: "ISBN" }],
          rights: [],
          bundledContent: [],
          id: "ebook-epub-adobe",
          name: "EPUB eBook",
          onSaleDateUtc: "2014-10-07T04:00:00Z",
          fileSize: 553523,
          isbn: "9781250035615",
        },
        {
          isBundleParent: false,
          hasAudioSynchronizedText: false,
          identifiers: [
            {
              value: "fcccc86a-bd13-3e81-8462-6223cdbf9e72",
              type: "KoboBookID",
            },
          ],
          rights: [],
          bundledContent: [],
          id: "ebook-kobo",
          name: "Kobo eBook",
          onSaleDateUtc: "2014-10-07T04:00:00Z",
        },
      ],
      publisherAccount: { name: "Macmillan Publishers", id: "6222" },
      estimatedReleaseDate: "2014-10-07T04:00:00Z",
      subtitle: "The Kyochiro Kaga Series Series, Book 1",
      series: "The Kyochiro Kaga",
      description:
        '<P>"This smart and original mystery is a true page-turner... will baffle, surprise, and draw out suspicion until the final few pages. With each book, Higashino continues to elevate the modern mystery as an intense and inventive literary form."...',
      availableCopies: 0,
      ownedCopies: 3,
      luckyDayAvailableCopies: 0,
      luckyDayOwnedCopies: 0,
      holdsCount: 8,
      holdsRatio: 3,
      estimatedWaitDays: 42,
      availabilityType: "normal",
      id: "1647024",
      firstCreatorName: "Keigo Higashino",
      title: "Malice--A Mystery",
      sortTitle: "MaliceA Mystery The Kyochiro Kaga Series Series Book 01",
      starRating: 3.8,
      starRatingCount: 153,
      publishDate: "2014-10-07T04:00:00Z",
      publishDateText: "10/07/2014",
      reserveId: "4bf78a9c-6fae-4651-ba93-2ef2cfcfdac5",
    },
  ],
  links: {
    self: { page: 1, pageText: "1" },
    first: { page: 1, pageText: "1" },
    last: { page: 1, pageText: "1" },
  },
  totalItemsText: "2",
}

export type OverdriveSearchResponse = typeof OVERDRIVE_SEARCH_RESPONSE

const OVERDRIVE_DETAIL_RESPONSE = [
  {
    firstCreatorId: 376472,
    youngAdultEligible: false,
    juvenileEligible: false,
    visitorEligible: false,
    isPreReleaseTitle: false,
    isPublicPerformanceAllowed: false,
    isPublicDomain: false,
    isBundledChild: false,
    unitsSold: 118,
    popularity: 354,
    subjects: [
      {
        name: "Fiction",
        id: "26",
      },
      {
        name: "Mystery",
        id: "57",
      },
    ],
    bisacCodes: ["FIC022020", "FIC022080"],
    bisac: [
      {
        description: "Fiction / Mystery & Detective / Police Procedural",
        code: "FIC022020",
      },
      {
        description:
          "FICTION / Mystery & Detective / International Crime & Mystery",
        code: "FIC022080",
      },
    ],
    levels: [],
    creators: [
      {
        id: 376472,
        role: "Author",
        name: "Keigo Higashino",
      },
      {
        id: 365795,
        role: "Narrator",
        name: "P.J. Ochlan",
      },
    ],
    languages: [
      {
        name: "English",
        id: "en",
      },
    ],
    ratings: {
      maturityLevel: {
        name: "General content",
        id: "generalcontent",
      },
      naughtyScore: {
        name: "General content",
        id: "GeneralContent",
      },
    },
    reviewCounts: {
      publisherSupplier: 0,
      premium: 2,
    },
    publisher: {
      name: "Macmillan Audio",
      id: "2166",
    },
    keywords: [
      "Investigators",
      "books on tape",
      "Crime Thrillers",
      "audiobooks",
      "murder mysteries",
      "Japan",
      "police detective",
      "audio books",
      "Genre Fiction",
      "mystery writers",
      "mystery series",
      "asian literature",
      "japanese authors",
      "mystery thriller suspense",
      "japanese novelist",
      "japanese mysteries",
      "crime investigation",
      "asian crime",
      "award winning mysteries",
      "japanese best sellers",
      "japanese cops",
      "mid summers equation",
    ],
    sample: {
      href: "https://samples.overdrive.com/?crid=d389f91e-4cac-42a6-9f4d-2d353ab1ffef&.epub-sample.overdrive.com",
    },
    constraints: {
      isDisneyEulaRequired: false,
    },
    type: {
      name: "Audiobook",
      id: "audiobook",
    },
    covers: {
      cover150Wide: {
        primaryColor: {
          rgb: {
            blue: 207,
            green: 213,
            red: 250,
          },
          hex: "#FAD5CF",
        },
        width: 150,
        height: 200,
        href: "https://img1.od-cdn.com/ImageType-150/1493-1/D38/9F9/1E/{D389F91E-4CAC-42A6-9F4D-2D353AB1FFEF}Img150.jpg",
      },
      cover300Wide: {
        primaryColor: {
          rgb: {
            blue: 205,
            green: 213,
            red: 250,
          },
          hex: "#FAD5CD",
        },
        width: 300,
        height: 400,
        href: "https://img1.od-cdn.com/ImageType-400/1493-1/D38/9F9/1E/{D389F91E-4CAC-42A6-9F4D-2D353AB1FFEF}Img400.jpg",
      },
      cover510Wide: {
        primaryColor: {
          rgb: {
            blue: 205,
            green: 213,
            red: 250,
          },
          hex: "#FAD5CD",
        },
        width: 510,
        height: 680,
        href: "https://img1.od-cdn.com/ImageType-100/1493-1/{D389F91E-4CAC-42A6-9F4D-2D353AB1FFEF}Img100.jpg",
      },
    },
    formats: [
      {
        isBundleParent: false,
        hasAudioSynchronizedText: false,
        identifiers: [
          {
            value: "9781427264527",
            type: "ISBN",
          },
          {
            value: "macmillan_audio#9781427264527",
            type: "8",
          },
          {
            value: "9781427278593",
            type: "LibraryISBN",
          },
        ],
        rights: [],
        bundledContent: [],
        sample: {
          href: "https://samples.overdrive.com/?crid=d389f91e-4cac-42a6-9f4d-2d353ab1ffef&.epub-sample.overdrive.com",
        },
        id: "audiobook-overdrive",
        name: "OverDrive Listen audiobook",
        onSaleDateUtc: "2016-02-23T00:00:00Z",
        fileSize: 335096264,
        isbn: "9781427278593",
        duration: "11:38:07",
      },
      {
        isBundleParent: false,
        hasAudioSynchronizedText: false,
        identifiers: [
          {
            value: "9781427264527",
            type: "ISBN",
          },
          {
            value: "macmillan_audio#9781427264527",
            type: "8",
          },
          {
            value: "9781427278593",
            type: "LibraryISBN",
          },
        ],
        rights: [],
        bundledContent: [],
        sample: {
          href: "https://excerpts.cdn.overdrive.com/FormatType-425/1493-1/2587716-AMidsummersEquation.mp3",
        },
        id: "audiobook-mp3",
        name: "MP3 audiobook",
        partCount: 10,
        onSaleDateUtc: "2016-02-23T00:00:00Z",
        fileSize: 335644094,
        isbn: "9781427278593",
        duration: "11:28:53",
      },
    ],
    publisherAccount: {
      name: "Macmillan Audio",
      id: "3606",
    },
    id: "2587716",
    firstCreatorName: "Keigo Higashino",
    title: "A Midsummer's Equation",
    sortTitle: "Midsummers Equation Detective Galileo Series Book 03",
    starRating: 3.9,
    starRatingCount: 122,
    edition: "Unabridged",
    publishDate: "2016-02-23T00:00:00Z",
    publishDateText: "02/23/2016",
    estimatedReleaseDate: "2016-02-23T00:00:00Z",
    isBundleChild: false,
    description:
      "<p>Manabu Yukawa, the physicist known as 'Detective Galileo,' has traveled to Hariguara, a once-popular summer resort town that has fallen on hard times. He is there to speak at a conference on a planned underwater mining operation, which has sharply divided the town. One faction is against the proposed operation, concerned about the environmental impact on the area, known for its pristine waters. The other faction, seeing no future in the town as it is, believes its only hope lies in the development project.<p>The night after the tense panel discussion, one of the resort's guests is found dead on the seashore at the base of the local cliffs. The local police at first believe it was a simple accident&#8212;that he wandered over the edge while walking on unfamiliar territory in the middle of the night. But when they discover that the victim was a former policeman and that the cause of death was carbon monoxide poisoning, they begin to suspect he was murdered, and his body tossed off the cliff to misdirect the police.<p>As the police try to uncover where Tsukahara was killed and why, Yukawa finds himself enmeshed in yet another confounding case of murder. In a series of twists as complex and surprising as any in Higashino's brilliant, critically acclaimed work, Galileo uncovers the hidden relationship behind the tragic events that led to this murder.",
    fullDescription:
      "<p>Manabu Yukawa, the physicist known as 'Detective Galileo,' has traveled to Hariguara, a once-popular summer resort town that has fallen on hard times. He is there to speak at a conference on a planned underwater mining operation, which has sharply divided the town. One faction is against the proposed operation, concerned about the environmental impact on the area, known for its pristine waters. The other faction, seeing no future in the town as it is, believes its only hope lies in the development project.<p>The night after the tense panel discussion, one of the resort's guests is found dead on the seashore at the base of the local cliffs. The local police at first believe it was a simple accident&#8212;that he wandered over the edge while walking on unfamiliar territory in the middle of the night. But when they discover that the victim was a former policeman and that the cause of death was carbon monoxide poisoning, they begin to suspect he was murdered, and his body tossed off the cliff to misdirect the police.<p>As the police try to uncover where Tsukahara was killed and why, Yukawa finds himself enmeshed in yet another confounding case of murder. In a series of twists as complex and surprising as any in Higashino's brilliant, critically acclaimed work, Galileo uncovers the hidden relationship behind the tragic events that led to this murder.",
    shortDescription:
      "<p>Manabu Yukawa, the physicist known as 'Detective Galileo,' has traveled to Hariguara, a once-popular summer resort town that has fallen on hard times. He is there to speak at a conference on a planned underwater mining operation, which has sharply divided the town. One faction is against the proposed operation, concerned about the environmental impact on the area, known for its pristine waters. The other faction, seeing no future in the town as it is, believes its only hope lies in the development project.<p>The night after the tense panel discussion, one of the resort's guests is found dead on the seashore at the base of the local cliffs. The local police at first believe it was a simple accident&#8212;that he wandered over the edge while walking on unfamiliar territory in the middle of the night. But when they discover that the victim was a former policeman and that the cause of death was carbon monoxide poisoning, they begin to suspect he was murdered, and his body tossed off...",
    series: "Detective Galileo",
    subtitle: "Detective Galileo Series, Book 3",
    reserveId: "d389f91e-4cac-42a6-9f4d-2d353ab1ffef",
  },
]

export type OverdriveDetailResponse = typeof OVERDRIVE_DETAIL_RESPONSE

export type SFEvent = { syncId: string }

export const LOCAL_STORAGE = {
  "dewey:sentry.identity":
    '"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJyZWFkaXZlcnNlIiwiaXNzIjoic2VudHJ5IiwiY2hpcCI6eyJpZCI6ImM5NTc3ZThlLTgwZmQtNGViMy04YzhjLWJlYTVhMWIxZjk2YiIsInByaSI6IjQ1MTk4ODBmLWQzZDEtNDE0Zi1hMzFiLTUzYzBiMDQzZTNmOCIsImFnIjoxMDIzMTE2NywiYWNjb3VudHMiOlt7ImFnIjoxMDIzMTE2NywiaWQiOiI2MDY4Njg1NSIsInR5cCI6ImxpYnJhcnkiLCJjYXJkcyI6W3siaWQiOiI0NDgxMTk5NCIsIm5hbWUiOiIyNzEzMTA1NzY3Mzg0MiIsImxpYiI6eyJpZCI6IjI0MyIsImtleSI6InRvcm9udG8ifX1dfSx7ImFnIjoxMDIzMTE2NywiaWQiOiI0NTIzNjY1MiIsInR5cCI6ImxpYnJhcnkiLCJjYXJkcyI6W3siaWQiOiIzMDIzODYwNiIsIm5hbWUiOiJueSIsImxpYiI6eyJpZCI6IjM3Iiwia2V5IjoibnlwbCJ9fV19LHsiYWciOjEwMjMxMTY3LCJpZCI6IjQ1MjM2MzM1IiwidHlwIjoibGlicmFyeSIsImNhcmRzIjpbeyJpZCI6IjMwMjM4MzI3IiwibmFtZSI6IjI5MDY1MDM4NzA3MDk3IiwibGliIjp7ImlkIjoiMTUzIiwia2V5IjoiY2FsZ2FyeSJ9fV19XX19.XJD8tRBH8sAgEhiXN_huWnw-T817b6ABrmR73Kf4Ew4Gjr7kPZ9sNNdhskMdcHhccwAcmUqYaek11Bd0UPI-A-1CyErfhikx54G-kMb6UGy3V0heMBc_wd2S3U5RWL5y2cjmiakMOrJxTFaHO3QnHOwTcl8gFPGzFjeBka0xbSImWaT1a8vd2h6WQJQilufJ5dQURg7acyM2V6ZXLsPoovJsowxy4JjR7myzSoTIRhG_Gtsuw3RTTRygjBmNVXKeQtOZP0pe0Vh4o72zuJ0_Zsb-Vu223T9vYtomKJhOpy6KNOpgPco3DK9v6lZpE0gOxuHR3ihBTX__z1afXyJHAw"',
  "dewey:migration:b013": '{"del":{},"add":{},"exp":1637631087228}',
  "dewey:migration:b012": '{"del":{},"add":{},"exp":1637631087228}',
  "dewey:migration:b009": '{"del":{},"add":{},"exp":1637631087227}',
  "dewey:patron:loan:all":
    '{"all":[{"websiteId":"153","cardId":"30238327","titleId":"2163589","reserveId":"32374baa-e560-489f-a14b-2c62616ca7be","holding":{"titleId":"2163589","isOwned":true,"isAvailable":false,"copiesOwned":1,"copiesAvailable":0,"holdsCount":0,"originalCopiesOwned":1},"createTime":1634789332000,"expireTime":1636603732000,"fulfiller":{"websiteId":"153","fulfillments":[{"fulfillmentType":"bifocal","fulfillmentSubtype":"ebook-overdrive","formats":["book"],"isMemorable":true,"isLockedIn":false,"hasSample":true,"sampleURL":"https://samples.overdrive.com/?crid=32374baa-e560-489f-a14b-2c62616ca7be&.epub-sample.overdrive.com"},{"fulfillmentType":"epub","fulfillmentSubtype":"ebook-epub-adobe","formats":["book"],"hasDRM":true,"isLockedIn":false,"hasSample":false,"sampleURL":null}]},"renewableTime":1636344532000,"returnableTime":1635039100981,"downloader":{"urls":{},"rosterIds":[],"totalBytes":0,"downloadPercent":null}}]}',
  "dewey:patron:choices":
    '{"fulfillment:preferences":{},"fulfillment:choices":{}}',
  "dewey:migration:b004": '{"del":{},"add":{},"exp":1637631087226}',
  "dewey:migration:b008":
    '{"del":{},"add":{"title:all":"<object>"},"exp":1637631087227}',
  "dewey:migration:b010": '{"del":{},"add":{},"exp":1637631087227}',
  "dewey:migration:b006": '{"del":{},"add":{},"exp":1637631087226}',
  "dewey:_bank-version": "17",
  "dewey:patron:hold:all":
    '{"all":[{"websiteId":"243","cardId":"44811994","titleId":"3469939","holding":{"titleId":"3469939","isOwned":true,"isAvailable":false,"copiesOwned":4,"copiesAvailable":0,"holdsCount":14,"position":8,"estimatedWaitDays":46,"originalPosition":8,"originalCopiesOwned":4},"createTime":1632010727763,"fulfiller":{"fulfillments":[{"fulfillmentType":"bifocal","fulfillmentSubtype":"ebook-overdrive","formats":["book"],"isMemorable":true,"isLockedIn":false,"hasSample":true,"sampleURL":"https://samples.overdrive.com/?crid=daf964a9-f22f-4061-94ff-562c9d840d02&.epub-sample.overdrive.com"},{"fulfillmentType":"epub","fulfillmentSubtype":"ebook-epub-adobe","formats":["book"],"hasDRM":true,"isLockedIn":false,"hasSample":false,"sampleURL":null}]},"suspendTime":0,"emailAddress":"","autoBorrowHold":false},{"websiteId":"243","cardId":"44811994","titleId":"5808586","holding":{"titleId":"5808586","isOwned":true,"isAvailable":false,"copiesOwned":65,"copiesAvailable":0,"holdsCount":278,"position":126,"estimatedWaitDays":58,"originalPosition":126,"originalCopiesOwned":65},"createTime":1631478270530,"fulfiller":{"fulfillments":[{"fulfillmentType":"bifocal","fulfillmentSubtype":"ebook-overdrive","formats":["book"],"isMemorable":true,"isLockedIn":false,"hasSample":true,"sampleURL":"https://samples.overdrive.com/?crid=791c6476-c5d0-404e-a5d0-713dce6d989c&.epub-sample.overdrive.com"},{"fulfillmentType":"epub","fulfillmentSubtype":"ebook-epub-adobe","formats":["book"],"hasDRM":true,"isLockedIn":false,"hasSample":false,"sampleURL":null}]},"suspendTime":0,"emailAddress":"","autoBorrowHold":false},{"websiteId":"243","cardId":"44811994","titleId":"5694481","holding":{"titleId":"5694481","isOwned":true,"isAvailable":false,"copiesOwned":37,"copiesAvailable":0,"holdsCount":116,"position":28,"estimatedWaitDays":42,"originalPosition":28,"originalCopiesOwned":37},"createTime":1630208932700,"fulfiller":{"fulfillments":[{"fulfillmentType":"bifocal","fulfillmentSubtype":"ebook-overdrive","formats":["book"],"isMemorable":true,"isLockedIn":false,"hasSample":true,"sampleURL":"https://samples.overdrive.com/?crid=50423d5e-40ef-4709-a82d-db76adf0903f&.epub-sample.overdrive.com"},{"fulfillmentType":"epub","fulfillmentSubtype":"ebook-epub-adobe","formats":["book"],"hasDRM":true,"isLockedIn":false,"hasSample":false,"sampleURL":null}]},"suspendTime":1635328338340,"isRedeliverable":true,"isRedeliveringAutomatically":true,"emailAddress":"","autoBorrowHold":false},{"websiteId":"37","cardId":"30238606","titleId":"5787868","holding":{"titleId":"5787868","isOwned":true,"isAvailable":false,"copiesOwned":5,"copiesAvailable":3,"holdsCount":1,"position":1,"estimatedWaitDays":3,"originalPosition":1,"originalCopiesOwned":5},"createTime":1627239519737,"fulfiller":{"fulfillments":[{"fulfillmentType":"bifocal","fulfillmentSubtype":"ebook-overdrive","formats":["book"],"isMemorable":true,"isLockedIn":false,"hasSample":true,"sampleURL":"https://samples.overdrive.com/?crid=38d8b266-42a1-406b-9bd6-3362979587ea&.epub-sample.overdrive.com"},{"fulfillmentType":"epub","fulfillmentSubtype":"ebook-epub-adobe","formats":["book"],"hasDRM":true,"isLockedIn":false,"hasSample":false,"sampleURL":null},{"fulfillmentType":"kindle","fulfillmentSubtype":"ebook-kindle","formats":["book"],"isMemorable":true,"isLockedIn":false,"hasSample":false,"sampleURL":null}]},"suspendTime":1635646154940,"isRedeliverable":true,"emailAddress":"","autoBorrowHold":false},{"websiteId":"153","cardId":"30238327","titleId":"3994836","holding":{"titleId":"3994836","isOwned":true,"isAvailable":true,"copiesOwned":39,"copiesAvailable":0,"holdsCount":45,"position":42,"estimatedWaitDays":0,"originalPosition":42,"originalCopiesOwned":39},"createTime":1634790252107,"expireTime":1635089272933,"fulfiller":{"fulfillments":[{"fulfillmentType":"bifocal","fulfillmentSubtype":"ebook-overdrive","formats":["book"],"isMemorable":true,"isLockedIn":false,"hasSample":true,"sampleURL":"https://samples.overdrive.com/?crid=1b06f42d-2233-4600-b207-7d298aa61772&.epub-sample.overdrive.com"},{"fulfillmentType":"epub","fulfillmentSubtype":"ebook-epub-adobe","formats":["book"],"hasDRM":true,"isLockedIn":false,"hasSample":false,"sampleURL":null}]},"suspendTime":0,"isAvailable":true,"isRedeliverable":true,"emailAddress":"","autoBorrowHold":false}]}',
  "dewey:library:all":
    '{"all":[{"websiteId":"243","baseKey":"toronto","type":"Public Library","logo":{"url":"https://thunder.cdn.overdrive.com/logo-resized/1357?1566916520"},"urls":{"home":"http://www.torontopubliclibrary.ca/","cardAcquisition":"http://www.torontopubliclibrary.ca/using-the-library/your-library-card/","support":"https://frontline.overdrive.com/?Lib=Toronto+Public+Library&CRID=1357&edge=true&Key=toronto"},"hasInstantCards":false,"visitableWebsiteIds":[],"name":"Toronto Public Library","colors":[{"hex":"#001c71","rgb":[0,28,113]},{"hex":"#0077c8","rgb":[0,119,200]}]},{"websiteId":"37","baseKey":"nypl","type":"Public Library","logo":{"url":"https://thunder.cdn.overdrive.com/logos/crushed/837.png?1"},"urls":{"home":"https://www.nypl.org/","cardAcquisition":"https://www.nypl.org/library-card","support":"https://frontline.overdrive.com/?Lib=New+York+Public+Library&edge=true&Key=nypl"},"promotesKindle":true,"hasInstantCards":false,"visitableWebsiteIds":[],"activatedAt":1635039132984,"name":"New York Public Library","colors":[{"hex":"#665f55","rgb":[102,95,85]},{"hex":"#009cd4","rgb":[0,156,212]}]},{"websiteId":"153","baseKey":"calgary","type":"Public Library","logo":{"url":"https://thunder.cdn.overdrive.com/logos/crushed/1194.png?1"},"urls":{"home":"https://calgarylibrary.ca/","support":"https://frontline.overdrive.com/?Lib=Calgary+Public+Library&CRID=1194&edge=true&Key=calgary"},"hasInstantCards":false,"visitableWebsiteIds":[],"name":"Calgary Public Library","colors":[{"hex":"#6b706a","rgb":[107,112,106]},{"hex":"#47bac9","rgb":[71,186,201]}]}]}',
  "dewey:notifier:subscriptions":
    '[[],["academy-lesson","loan-expiring","loan-expired","hold-ready","hold-lapsing","hold-lapsed","hold-borrowed","hold-rescheduled","notify-me-author","notify-me-series"],[],["notifier-upgrade","notifier-repair","card-expired","cards-expired","wish-list-sync"]]',
  "dewey:daemon:default-tags":
    '{"wish-list-sync":{"counts":{"total":0,"cards":{}}},"borrowed":{"used":true}}',
  "dewey:migration:b014":
    '{"del":{},"add":{"patron:choices > fulfillment:preferences":"<object>","patron:choices > fulfillment:choices":"<object>"},"exp":1637631087228}',
  "dewey:migration:b016": '{"del":{},"add":{},"exp":1637631087228}',
  "dewey:sentry.chip": '"c9577e8e-80fd-4eb3-8c8c-bea5a1b1f96b"',
  "dewey:migration:b015":
    '{"del":{},"add":{"vandal:queue":"<object>"},"exp":1637631087228}',
  "dewey:daemon:engagement":
    '{"installedAt":1635039087229,"launchedAt":1635039087229,"foregroundedAt":1635039087229}',
  "dewey:notifier:notification:all":
    '{"all":[{"category":"hold-rescheduled","id":"44811994-5694481","details":{"titleId":"5694481","websiteId":"243","cardId":"44811994","possessionSlug":"44811994-5694481"},"dismissable":true,"createdAt":1635039098062,"provisional":false},{"category":"hold-ready","id":"30238327-3994836","details":{"titleId":"3994836","websiteId":"153","cardId":"30238327","possessionSlug":"30238327-3994836"},"dismissable":true,"createdAt":1635039098062,"provisional":false}]}',
  "dewey:patron:card:all":
    '{"all":[{"cardId":"44811994","cardName":"27131057673842","createTime":1635027300000,"puid":"101963932","websiteId":"243","advantageKey":"toronto","accounts":[-1],"ilsName":"toronto","username":"27131057673842","lendingPeriods":{"book":{"options":[[7,"days"],[14,"days"],[21,"days"]],"preference":[21,"days"],"luckyDay":7},"audiobook":{"options":[[7,"days"],[14,"days"],[21,"days"]],"preference":[21,"days"],"luckyDay":7},"magazine":{"options":[[7,"days"],[14,"days"],[21,"days"]],"preference":[21,"days"]}},"isVisiting":false,"canPlaceHolds":true},{"cardId":"30238606","cardName":"ny","createTime":1595729599000,"puid":"73119769","websiteId":"37","advantageKey":"nypl","accounts":[-1],"ilsName":"default","username":"23333999978240","lendingPeriods":{"book":{"options":[[7,"days"],[14,"days"],[21,"days"]],"preference":[21,"days"]},"audiobook":{"options":[[7,"days"],[14,"days"],[21,"days"]],"preference":[14,"days"]},"magazine":{"options":[[7,"days"],[14,"days"],[21,"days"]],"preference":[14,"days"]}},"isVisiting":false,"canPlaceHolds":true},{"cardId":"30238327","cardName":"29065038707097","createTime":1595728435000,"puid":"82753696","websiteId":"153","advantageKey":"calgary","accounts":[-1],"ilsName":"calgary","username":"29065038707097","lendingPeriods":{"book":{"options":[[7,"days"],[14,"days"],[21,"days"]],"preference":[21,"days"],"luckyDay":7},"audiobook":{"options":[[7,"days"],[14,"days"],[21,"days"]],"preference":[21,"days"],"luckyDay":7},"magazine":{"options":[[21,"days"]],"preference":[21,"days"]}},"isVisiting":false,"canPlaceHolds":true}]}',
  "dewey:patron:dismissals": '{"footer:tutorial":1635039087}',
  "dewey:patron:activity:all":
    '{"all":[{"action":"borrow","createTime":1634789332000,"titleId":"2163589","cardId":"30238327","websiteId":"153","meta":{"time":1814400000}},{"action":"hold","createTime":1632010727763,"titleId":"3469939","cardId":"44811994","websiteId":"243"},{"action":"hold","createTime":1631478270530,"titleId":"5808586","cardId":"44811994","websiteId":"243"},{"action":"hold","createTime":1630208932700,"titleId":"5694481","cardId":"44811994","websiteId":"243"},{"action":"hold","createTime":1627239519737,"titleId":"5787868","cardId":"30238606","websiteId":"37"},{"action":"hold","createTime":1634790252107,"titleId":"3994836","cardId":"30238327","websiteId":"153"}]}',
  "dewey:migration:b017": '{"del":{},"add":{},"exp":1637631087228}',
  "dewey:migration:b011": '{"del":{},"add":{},"exp":1637631087227}',
  "dewey:migration:b005":
    '{"del":{},"add":{"patron:choices":"<object>","patron:dismissals":"<object>"},"exp":1637631087226}',
  "dewey:migration:b007": '{"del":{},"add":{},"exp":1637631087227}',
  "dewey:scribe:state":
    '{"tid":"e7c00e4e-30a1-4e98-b7e7-c84ddf5622fe","sessions":[]}',
  "dewey:title:all":
    '{"all":[{"slug":"2163589","title":"A Midsummer\'s Equation","subtitle":"Detective Galileo Series, Book 3","format":"book","series":{"name":"Detective Galileo"},"cover":{"color":[248,207,201],"url":"https://img1.od-cdn.com/ImageType-100/2390-1/{32374BAA-E560-489F-A14B-2C62616CA7BE}Img100.jpg"},"creators":{"Creator":[{"name":"Keigo Higashino","id":376472}]},"subjects":[{"name":"Fiction","id":"26"},{"name":"Mystery","id":"57"}],"audiences":[],"stars":{"rating":4.2,"ratingCount":46},"publicationTime":1456203600000},{"slug":"3469939","title":"Death by Dumpling","subtitle":"Noodle Shop Mystery Series, Book 1","format":"book","series":{"name":"Noodle Shop Mystery"},"cover":{"color":[214,61,47],"url":"https://img1.od-cdn.com/ImageType-100/2390-1/{DAF964A9-F22F-4061-94FF-562C9D840D02}Img100.jpg"},"creators":{"Creator":[{"name":"Vivien Chien","id":1391665}]},"subjects":[{"name":"Fiction","id":"26"},{"name":"Mystery","id":"57"}],"audiences":[],"stars":{"rating":3.7,"ratingCount":114},"publicationTime":1522108800000,"isPrerelease":false},{"slug":"5808586","title":"The Soulmate Equation","format":"book","cover":{"color":[255,200,17],"url":"https://img1.od-cdn.com/ImageType-100/0439-1/{791C6476-C5D0-404E-A5D0-713DCE6D989C}Img100.jpg"},"creators":{"Creator":[{"name":"Christina Lauren","id":209120}]},"subjects":[{"name":"Fiction","id":"26"},{"name":"Literature","id":"49"},{"name":"Romance","id":"77"},{"name":"Humor (Fiction)","id":"123"}],"audiences":[],"stars":{"rating":4.1,"ratingCount":620},"publicationTime":1621296000000,"isPrerelease":false},{"slug":"5694481","title":"Neon Gods","subtitle":"Dark Olympus Series, Book 1","format":"book","series":{"name":"Dark Olympus"},"cover":{"color":[3,4,6],"url":"https://img1.od-cdn.com/ImageType-100/0174-1/{50423D5E-40EF-4709-A82D-DB76ADF0903F}Img100.jpg"},"creators":{"Creator":[{"name":"Katee Robert","id":329001}]},"subjects":[{"name":"Fiction","id":"26"},{"name":"Mythology","id":"58"},{"name":"Romance","id":"77"}],"audiences":[],"stars":{"rating":3.6,"ratingCount":129},"publicationTime":1622505600000,"isPrerelease":false},{"slug":"5787868","title":"The Tiger Mom\'s Tale","format":"book","cover":{"color":[240,60,46],"url":"https://img1.od-cdn.com/ImageType-100/1523-1/{38D8B266-42A1-406B-9BD6-3362979587EA}Img100.jpg"},"creators":{"Creator":[{"name":"Lyn Liao Butler","id":2351178}]},"subjects":[{"name":"Fiction","id":"26"},{"name":"Literature","id":"49"}],"audiences":[],"stars":{"rating":2.6,"ratingCount":19},"publicationTime":1625529600000,"isPrerelease":false},{"slug":"3994836","title":"The Silent Patient","format":"book","cover":{"color":[248,245,238],"url":"https://img1.od-cdn.com/ImageType-100/2390-1/{1B06F42D-2233-4600-B207-7D298AA61772}Img100.jpg"},"creators":{"Creator":[{"name":"Alex Michaelides","id":1644558}]},"subjects":[{"name":"Fiction","id":"26"},{"name":"Suspense","id":"86"},{"name":"Thriller","id":"100"}],"audiences":[],"stars":{"rating":3.9,"ratingCount":4990},"publicationTime":1549324800000,"isPrerelease":false}]}',
}

export type LocalStorage = typeof LOCAL_STORAGE
